### PR TITLE
Organize recipes + Move WIRELESS.cfg to meta-mistysom

### PR DESCRIPTION
**Pull request by matinlotfali**
In this pull request, I am moving `WIRELESS.cfg` to `meta-mistysom` because it is shared between **rzg2l** and **rzv2l**.
I am also moving wireless-related recipes into `recipes-connectivity`

### CODE REVIEW

**Review by mistyron — COMMENTED** [review]
Would it be a good time to also move the other kernel config fragments from mw_fragments/?

**Review by mistyron — CHANGES_REQUESTED** [review]
Would it be a good time to also move the other kernel config fragments from mw_fragments/?

**Comment by matinlotfali** [comment]
> Would it be a good time to also move the other kernel config fragments from mw_fragments/?

Sure. But I don't know which ones are specific to g2l or v2l and which are common.
I only know that `WIRELESS.cfg` is common.

**Comment by mistyron** [comment]
@matinlotfali  Yes, all the `mw_fragments/` are common and apply to both,  V2L and G2L

**Comment by gfinlay** [comment]
@Matin I'll sync with you Wednesday to arrange changes to move over my
additional mw_fragments .CFG files which are common to both G2L and v2l to
go to the meta-mistysom repo.

**Review by mistyron — APPROVED** [review]
LGTM

**Pull request merged**
