### PR TITLE
Fix testing patches 

### PR DESCRIPTION
**Pull request by matinlotfali**
The patch was not working for some reason. So I recreated a patch and replaced it with the older one. You can see their differences. Apparently the order of patches matters.

### CODE REVIEW

**Review by mistyron — APPROVED** [review]
Thanks for fixing this Matin, LGTM

@vlaltzic  make sure you update you copy of `develop` once after it got merged to test this fix (as it relates to the PHY bring-up).

**Review by mistyron — CHANGES_REQUESTED** [review]
Thanks for fixing this Matin, LGTM but 
copy this to the meta-mistysom/recipes-kernel/linux/smarc-rzg2l/ directory as well, please!

@vlaltzic make sure you update you copy of develop once after it got merged to test this fix (as it relates to the PHY bring-up).

**Comment by matinlotfali** [comment]
> copy this to the meta-mistysom/recipes-kernel/linux/smarc-rzg2l/ directory as well

That would be a different patch because it needs to be applied to a different device tree file.

**Comment by mistyron** [comment]
That is right but it can be merged with the same PR, it mitigates the risk of it getting forgotten.

**Comment by matinlotfali** [comment]
I learned that the patches are not able to be used in any order and simultaneously. 
So I changed them from git patches into simple concatenates.

**Review by mistyron — APPROVED** [review]
Good stuff, LGTM! Thanks!

**Pull request merged**
