### PR TITLE
Create GitHub Actions for release procedure

### PR DESCRIPTION
**Pull request by matinlotfali**
In this pull request, I am adding GitHub actions which do the following:

**- On push in develop:** creates a pull request from develop to master automatically.
**- When approved the "develop to master" pull request:** Fast Forward the master branch so both master and develop point to the same commit. (not any additional merge commit).
**- On push in master:** creates/updates a draft of a release with release notes automatically.

### CODE REVIEW

**Review by mistyron — COMMENTED** [review]
Not si sure if I like this as it basically means that features go froma development branch directly into master without doing testing in develop, right? It doesn't entirely align with our branching model: 
image
There was no need for us to havce release branches uyntil now as we've "just" been testing straight out of develop (limited nmumber of people and commits). What are your thoughts on the topic?

**Comment by matinlotfali** [comment]
> Not si sure if I like this as it basically means that features go froma development branch directly into master without doing testing in develop, right?

No these GitHub actions would create a pull request but it needs to be approved and merged by us.

Similarly, a draft of release is generated but it needs to be reviewed, edited, and approved by us.

**Comment by matinlotfali** [comment]
I added this action:
- When approved the "develop to master" pull request: Fast Forward the master branch so both master and develop point to the same commit. (not any additional merge commit).

I added us as reviewers when the pull request is automatically created.

**Comment by mistyron** [comment]
> > Not si sure if I like this as it basically means that features go froma development branch directly into master without doing testing in develop, right?
> 
> No these GitHub actions would create a pull request but it needs to be approved and merged by us.
> 
> Similarly, a draft of release is generated but it needs to be reviewed, edited, and approved by us.

Ojh okay, I misunderstood then, Thanks for the clarification!

**Review by mistyron — APPROVED** [review]
Thanks for the clarification. LGTM :+1:

**Pull request merged**
