### PR TITLE
Add NodeJS

### PR DESCRIPTION
**Pull request by matinlotfali**
In this pull request, I am adding the `nodejs` recipe which includes the `npm` binary inside it.

### CODE REVIEW

**Review by mistyron — APPROVED** [review]
Excellent, LGTM! Thanks!

**Comment by mistyron** [comment]
@matinlotfali it appears like nodejs does not compile as integrated.... I received a lot of errors about missing patches, ended up manually upgrading the recipe to: https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/nodejs/nodejs_12.22.12.bb?h=dunfell and copying in the missing patches from: https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/nodejs/nodejs?h=dunfell but I could not get it to compile on Brennan's machine and ended up commenting it out from the bbappend to at least get him something that compiles succesfully, we'll have to look into this.... I'm not 100% sure what's up yet, mostly put this comment here to keep some of the information....

**Comment by mistyron** [comment]
@matinlotfali 
Even for me:  the build failed once with:
```
ERROR: Task (/home/yocto/rzv_vlp_v3.0.0/build/../meta-openembedded/meta-oe/recipes-devtools/nodejs/nodejs_12.21.0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6646 tasks of which 6100 didn't need to be rerun and 1 failed.
```
and I just re-invoked the build with 
```
$ bitbake mistysom-image
```
and the second time it finished succesfullly.... not sure yet what to make out of it 🤔

**Comment by matinlotfali** [comment]
@mistyron 
You can see that the `build-yocto` GitHub Action in this pull request is successful. So my guess is that there is something wrong with your cache management probably.

**Comment by mistyron** [comment]
> @mistyron You can see that the `build-yocto` GitHub Action in this pull request is successful. So my guess is that there is something wrong with your cache management probably.

Yeah, that was my thought as well but I have not been able to really point my finger at the cause of the issue yet. First time I saw it on Brennan's setup and then it appeared for me too.... but not always, I've since been able to compile it all successfully too. It's still a bit of a puzzle. I suggest we do not deal with it when it causes a problem again... might just have been some caching issue, right (but what speak against this is that Brennan didn't have a cache yet and compiled on a fresh system the first time)

**Pull request merged**
